version: "3.8"

services:
  app:
    container_name: wordpress
    image: wordpress:6.1.0-php8.0-apache
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wp
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis */
        define('WP_REDIS_HOST', getenv_docker('WORDPRESS_REDIS_HOST', 'redis'));
        define('WP_REDIS_PORT', getenv_docker('WORDPRESS_REDIS_PORT', 6379));
    volumes:
      - ./.wp/main:/var/www/html
      - ./themes/main:/var/www/html/wp-content/themes/base
  
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: wp
      MARIADB_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./.db/main/data:/var/lib/mysql

  redis:
    container_name: redis 
    image: redis:latest
    volumes:
      - redis:/data

volumes:
  wordpress:
  redis:
